# .github/workflows/douban.yml
name: douban
on: 
  workflow_dispatch:
  # push:
  schedule:    
  # - cron: "10 1 1 * *" # Every month 
  - cron: "5 */12 * * 1"

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: sholmes1412
        type: movie
        # status: mark 
        status: done 
        format: json
        dir: ./data/douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: sholmes1412
        type: book
        # status: mark 
        status: done  
        format: json
        dir: ./data/douban
  
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban data'
        add: './data/douban'
